flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R: R/fac.R
  tests: tests/testthat/test-fac.R
  vignettes: vignettes/factorial.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: Factorial
    open_vignette: true
    check: true
    document: true
    overwrite: ask
